### ISSUE TITLE
OBS Support v28 (QT6 update)

### ISSUE THREAD

**Issue by lindenkron** [univrsal/durchblick#1]
With v28 switching to QT6, plugin devs that relied on QT5 need to update for it to be compatible. Just a heads up, since this is one of my favourite and used plugins.

https://obsproject.com/forum/threads/obs-studio-28-0-beta.158248/

**Comment by univrsal** [comment]
RytoEX has already told me, I'll look into it. Hopefully it won't be too much effort

**Comment by univrsal** [comment]
The latest builds now use qt6
