### ISSUE TITLE
Mixed language bug when German 

### ISSUE THREAD

**Issue by Joluje** [univrsal/durchblick#2]
**Describe the bug**
Mixed language when language is set to German

**Expected behavior**
only German 

**Screenshots**
German:
![image](https://user-images.githubusercontent.com/96259116/188734249-169a7c9a-d5fa-48da-95ab-343691134462.png)
English:
![image](https://user-images.githubusercontent.com/96259116/188735091-99b2b5c0-b878-4611-a51b-f8314c90afaf.png)

**Comment by univrsal** [comment]
Closed with b27a73d468bfd427ea35b53cae571f78137a13f4
